### ISSUE TITLE
How to authentication with proxy server?

### ISSUE THREAD

**Issue by itmanvn** [liulilittle/VEthernet#3]
For example: username:password@server:port

**Comment by liulilittle** [comment]
Is this the issue your sent to me?

Example tun2socks code does not support socks5 account password authentication.

Wait for a period of time, can provide about tun2socks socks5 identity authentication example code support!

**Comment by liulilittle** [comment]
go here for updates!： https://github.com/liulilittle/VEthernet/releases/tag/1.0.0.5

**Comment by itmanvn** [comment]
great!!!
