### ISSUE TITLE
开启后运行游戏过程中，间隔几分钟时间就会出现数据丢包网络掉线的现象

### ISSUE THREAD

**Issue by yougl** [liulilittle/VEthernet#9]
请教一下，您开源的项目VEthernet，开启后运行游戏过程中，间隔几分钟时间就会出现数据丢包网络掉线的现象，游戏会提示断开连接重连，不知道您这边是否有遇到

**Comment by liulilittle** [comment]
没有遇到过这种问题，而且我推荐你改用：https://github.com/liulilittle/openppp2
